### ISSUE TITLE
Dual Excursion Funnel Emitter crash on tick

### ISSUE THREAD

**Issue by Aikoyori** [Fusion-Flux/Thinking-With-Portatos#78] opened 2022-12-14 12:56 UTC
[Here](https://mclo.gs/yDKEoTS) is the link to crash report.

Tried it on just Quilt & QSL+QFAPI+Portal Cubed and it crashes upon placement.

**Comment by asoji** [comment] 2022-12-15 09:19
Couldn't seem to reproduce the issue, were you placing it in a very specific way? 

Would you by any chance be able to provide a video of it happening too?

I'm also using QSL `v4.0.0-beta.24+0.68.0-1.19.2`, on Quilt Loader v0.17.7.

**Comment by Aikoyori** [comment] 2022-12-16 14:04
Here is a video with it happening.
https://user-images.githubusercontent.com/12034280/208115010-11bb806f-96ca-42f7-b2bc-361474715689.mp4

__

**Comment by Cart3r1234** [comment] 2023-02-05 22:10
This seems to have been fixed in dev builds, as I could not reproduce it by replicating what you did in the video.  Please test with a dev build (use this link to grab whatever is the latest at the time: https://nightly.link/Fusion-Flux/Portal-Cubed/workflows/build/1.19.2/Artifact.zip) and let us know if it still happens.

**Closed as completed by Cart3r1234** 2023-02-05 22:10 UTC

**Comment by Aikoyori** [comment] 2023-02-23 09:07
I tested on my own and the ALPHA version works just fine. Thanks for updating.
