### ISSUE TITLE
You can get stuck in a funnel if there are block in between you

### ISSUE THREAD

**Issue by Ch1216** [Fusion-Flux/Thinking-With-Portatos#52] opened 2022-05-26 14:51 UTC
https://youtu.be/R8sB-E7vW6A

A solution for this situation I suggest is to make it so you can go under and drop from funnels without having to go to the sides

**Comment by Gaming32** [comment] 2023-02-14 02:08
Does this not happen in Portal 2?

**Comment by Cart3r1234** [comment] 2023-02-14 02:14
> Does this not happen in Portal 2?

no, in portal 2 you can move out of the funnel in the direction you look, so if you look downwards and hold forward you can escape by falling out of the funnel.  The current idea is to make holding shift in a horizontal funnel make you drop out of it, but that has not been implemented yet.

**Comment by Gaming32** [comment] 2023-02-14 02:16
It's not a bug then, just a missing feature.

**Comment by Cart3r1234** [comment] 2023-02-14 02:19
Its a bit of both. Getting stuck in funnels is an unintended behavior, so that part of it is a bug, but the method of escaping that Portal 2 uses isn't implemented yet

**Comment by Cart3r1234** [comment] 2023-02-21 06:16
This has been fixed as of Fusion's latest commit.  Moving inside of a funnel now works closer to how it does in Portal 2, where walking forward while looking up/down changes your vertical position inside the funnel, allowing you to drop out below the funnel if you can't exit it horizontally.

**Closed as completed by Cart3r1234** 2023-02-21 06:16 UTC
